name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '19.9.0'
      - name: Setup package manager
        run: |
          npm config set fund false
          npm config set audit false
      - name: Install dependencies
        run: npm ci --no-optional
      - name: Lint source code
        run: npm run lint
      - name: Build Next App
        run: npm run build
      - name: Run unit tests
        run: npm test

  build-docker-image:
    needs: [build-and-test]
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ github.repository }}:latest
  
