name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '19.9.0'
          cache: 'npm'
      - name: Setup package manager
        run: |
          npm config set fund false
          npm config set audit false
      - name: Install dependencies
        run: npm ci --omit=optional
  
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '19.9.0'
          cache: 'npm'
      - name: Lint source code
        run: npm ci --omit=optional && npm run lint

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '19.9.0'
          cache: 'npm'
      - name: Build Next App
        run: npm ci --omit=optional && npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: .next

  unit-tests:
    needs: [lint, build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '19.9.0'
          cache: 'npm'
      - name: Run unit tests
        run: npm test
      - uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: .next
      
  build-docker-image:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: ${{ github.event_name == 'push' }}
          tags: ${{ github.repository }}:latest
  
